### ISSUE TITLE
大哥哥，求一个你编译好的ARM上的 ”Hadoop 3.3.4 Native Libraries“

### ISSUE THREAD

**Issue by fengyunhe** [vndroid/docker-library#1]
大哥哥，求一个你编译好的ARM上的 ”Hadoop 3.3.4 Native Libraries“，或者给个Dockerfile也行，我这边自己编译，多谢啦~

**Comment by vndroid** [comment]
Please visit my website https://wave.md/hadoop/ to download the Hadoop package (including native libraries).

**Comment by fengyunhe** [comment]
Thank you, you are handsome.
